### ISSUE TITLE
修改下错别字吧

### ISSUE THREAD

**Issue by TheStar4Fate** [wuapnjie/PoiShuhui-Kotlin#2]
"我像成为一个优秀的developer"->"我想成为一个优秀的developer"
加油吧！

**Comment by wuapnjie** [comment]
好的

在 2016年03月21日 15:21, liuzhenyu 写道:

**Comment by zhengzhou** [comment]
哈哈， @wuapnjie 我刚看到你的，好巧的是我也用kotlin 写了一个漫画软件，时间上也差不多。https://coding.net/u/buzz/p/NoMonster/git 
有时间一起做啊。

**Comment by wuapnjie** [comment]
恩，好呀～就是要等学校的一些事过去了才有时间，呜呜

**Comment by gguan** [comment]
Hi, 你好请问你在北京吗？我们在找安卓开发，有兴趣聊聊吗？～找不到你联系方式在这上留言不好意思。。

**Comment by TheStar4Fate** [comment]
@gguan 您是在问我吗？

**Comment by gguan** [comment]
@lzy26fate 哈哈其实是问项目主。。 我看了你有兴趣我们可以私聊哈我qq86627984
